dist: trusty
sudo: false
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
before_install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade virtualenv
install:
    - pip --version
    - virtualenv --version
    - git --version
    - |
        git clone https://github.com/MozillaSecurity/lithium.git --branch specifyInterestingnessModules --single-branch\
          ${TRAVIS_BUILD_DIR}/../lithiumInstallable
    - pip install --no-index --upgrade ${TRAVIS_BUILD_DIR}/../lithiumInstallable
before_script:
    - pip install --upgrade flake8 pylint
    - pip install --upgrade pytest-flake8 pytest-pylint
script:
    - py.test
    # -- START of lithium module tests --
    - "pushd $HOME"  # Do not test from the GitHub repo dir due to Python module intricacies
    - "pwd"  # Double-check the current directory
    - "python -c 'import lithium; print(lithium); print(dir(lithium))'"
    - "python -c 'import lithium; print(lithium.interestingness.crashes)'"
    # - "python -c 'import lithium; print(lithium.interestingness.diffTest)'"  # diffTest is not used outside of Lithium
    - "python -c 'import lithium; print(lithium.interestingness.envVars)'"
    - "python -c 'import lithium; print(lithium.interestingness.fileIngredients)'"
    - "python -c 'import lithium; print(lithium.interestingness.hangs)'"
    - "python -c 'import lithium; print(lithium.interestingness.outputs)'"
    # - "python -c 'import lithium; print(lithium.interestingness.range)'"  # shadows standard python function
    - "python -c 'import lithium; print(lithium.interestingness.timedRun)'"
    - "touch temp.js"
    - "python -m lithium outputs --timeout=2 temp.js ls temp.js"
    # - "python -m lithium range 1 2 outputs --timeout=2 temp.js ls temp.js"  # shadows standard python function
    # Invert the exit code for crashes and hangs, since running `ls` with temp.js is not supposed to be "interesting".
    - "! python -m lithium crashes --timeout=2 ls temp.js"
    # - "! python -m lithium range 1 2 crashes --timeout=2 ls temp.js"  # shadows standard python function
    - "! python -m lithium hangs 3 ls temp.js"
    # - "! python -m lithium range 1 2 hangs 3 ls temp.js"  # shadows standard python function
    - "rm temp.js"
    - "popd"
    # -- END of lithium module tests --
